name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  Build-and-Push-Container:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ secrets.ETHERSYS_GHCR_USER }}
          password: ${{ secrets.ETHERSYS_GHCR_PASS }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          tags: ghcr.io/ethersys/munin:latest,ghcr.io/ethersys/munin:2.0.57
